;将buf变量为首址的100个字节的存储单元清0
.386
DATA SEGMENT USE16
BUF DB "fdfakdjfklajdflkjsdf"
DATA ENDS
STACK SEGMENT USE16 STACK
DB 200H DUP(0)
STACK ENDS
CODE SEGMENT USE16
ASSUME CS:CODE,SS:STACK,ES:DATA;注意这里是ES与DATA关联，因为STOS只能改变ES:[DI]里的东西
BEGIN:
    MOV AX,DATA
    MOV ES,AX;给ES
    LEA DI,BUF
    MOV AL,0
    MOV CX,100
    REP STOSB;(AL)→ DS:[DI] ,无条件重复CX中的次数
    MOV AX,4CH;答案这里写的4C00H，我不知道它是不是写错了
    INT 21H
CODE ENDS
END BEGIN